"""Schemat bazowy — stan bazy po całym starym, ręcznym `_migrate()`.

To jest punkt zerowy adopcji Alembica, a nie „pierwsza migracja”: opisuje
schemat, jaki MealPilot miał w chwili wdrożenia Alembica. Instalacje sprzed
Alembica są doprowadzane do tego stanu przez `app.main._migrate()`, a potem
`alembic stamp` wpisuje tu tę rewizję (patrz `_run_migrations` w `app/main.py`).
Świeże instalacje dostają ten sam schemat, wykonując tę rewizję naprawdę.

Nie edytuj tego pliku — każda zmiana schematu to nowa rewizja.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-30

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Powtarza się w czterech tabelach; wyciągnięte, żeby linie mieściły się w limicie.
_OWNER_EXACTLY_ONE = "(owner_user_id IS NOT NULL) <> (owner_household_id IS NOT NULL)"

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("can_use_ai", sa.Boolean(), nullable=False),
        sa.Column("ai_monthly_token_limit", sa.Integer(), nullable=True),
        sa.Column("ai_monthly_cost_limit_cents", sa.Integer(), nullable=True),
        sa.Column("ai_used_tokens_this_month", sa.Integer(), nullable=False),
        sa.Column("ai_used_cost_cents_this_month", sa.Integer(), nullable=False),
        sa.Column("ai_usage_period_start", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("ui_prefs", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_prefix"), ["prefix"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "household_members",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("can_edit", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("household_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_household_members_household_id"), ["household_id"], unique=False)

    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("owner_household_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("prep_time", sa.Integer(), nullable=False),
        sa.Column("cook_time", sa.Integer(), nullable=False),
        sa.Column("kcal", sa.Float(), nullable=False),
        sa.Column("p", sa.Float(), nullable=False),
        sa.Column("f", sa.Float(), nullable=False),
        sa.Column("c", sa.Float(), nullable=False),
        sa.Column("hue", sa.Integer(), nullable=False),
        sa.Column("ingredients", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("meal_types", sa.JSON(), nullable=False),
        sa.Column("image_filename", sa.String(), nullable=True),
        sa.Column("is_meal_prep", sa.Boolean(), nullable=False),
        sa.Column("meal_prep_days", sa.Integer(), nullable=True),
        sa.Column("meal_prep_steps", sa.JSON(), nullable=False),
        sa.CheckConstraint(_OWNER_EXACTLY_ONE, name="ck_recipes_owner_exactly_one"),
        sa.ForeignKeyConstraint(
            ["owner_household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.create_index("ix_recipes_owner_household", ["owner_household_id"], unique=False)
        batch_op.create_index("ix_recipes_owner_user", ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "shopping_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("owner_household_id", sa.Integer(), nullable=True),
        sa.Column("week_start", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("checked", sa.Integer(), nullable=False),
        sa.Column("is_custom", sa.Integer(), nullable=False),
        sa.CheckConstraint(_OWNER_EXACTLY_ONE, name="ck_shop_owner_exactly_one"),
        sa.ForeignKeyConstraint(
            ["owner_household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "week_start", "name", "unit", name="uq_shop_user_week_name_unit"),
    )
    with op.batch_alter_table("shopping_items", schema=None) as batch_op:
        batch_op.create_index("ix_shop_owner_household_week", ["owner_household_id", "week_start"], unique=False)
        batch_op.create_index("ix_shop_owner_user_week", ["owner_user_id", "week_start"], unique=False)
        batch_op.create_index("ix_shop_user_week", ["user_id", "week_start"], unique=False)
        batch_op.create_index(batch_op.f("ix_shopping_items_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shopping_items_week_start"), ["week_start"], unique=False)

    op.create_table(
        "week_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("owner_household_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("entries", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(_OWNER_EXACTLY_ONE, name="ck_tpl_owner_exactly_one"),
        sa.ForeignKeyConstraint(
            ["owner_household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("week_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_week_templates_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_messages_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index("ix_agent_msg_conv_created", ["conversation_id", "created_at"], unique=False)

    op.create_table(
        "meal_plan_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("owner_household_id", sa.Integer(), nullable=True),
        sa.Column("week_start", sa.String(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("meal", sa.String(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.CheckConstraint(_OWNER_EXACTLY_ONE, name="ck_plan_owner_exactly_one"),
        sa.ForeignKeyConstraint(
            ["owner_household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meal_plan_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meal_plan_entries_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_meal_plan_entries_week_start"), ["week_start"], unique=False)
        batch_op.create_index("ix_plan_owner_household", ["owner_household_id", "week_start"], unique=False)
        batch_op.create_index("ix_plan_owner_user", ["owner_user_id", "week_start"], unique=False)
        batch_op.create_index("ix_plan_user_week", ["user_id", "week_start"], unique=False)

    op.create_table(
        "recipe_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "user_id", name="uq_note_recipe_user"),
    )
    with op.batch_alter_table("recipe_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_notes_recipe_id"), ["recipe_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_notes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recipe_ratings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "user_id", name="uq_rating_recipe_user"),
    )
    with op.batch_alter_table("recipe_ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ratings_recipe_id"), ["recipe_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ratings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "shopping_item_recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["shopping_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "recipe_id", name="uq_shop_item_recipe"),
    )
    with op.batch_alter_table("shopping_item_recipes", schema=None) as batch_op:
        batch_op.create_index("ix_shop_item_recipes_item", ["item_id"], unique=False)

    op.create_table(
        "agent_tool_uses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("tool_use_id", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("is_error", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["agent_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_tool_uses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_tool_uses_message_id"), ["message_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_tool_uses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_tool_uses_message_id"))

    op.drop_table("agent_tool_uses")
    with op.batch_alter_table("shopping_item_recipes", schema=None) as batch_op:
        batch_op.drop_index("ix_shop_item_recipes_item")

    op.drop_table("shopping_item_recipes")
    with op.batch_alter_table("recipe_ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ratings_user_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ratings_recipe_id"))

    op.drop_table("recipe_ratings")
    with op.batch_alter_table("recipe_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_notes_user_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_notes_recipe_id"))

    op.drop_table("recipe_notes")
    with op.batch_alter_table("meal_plan_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_plan_user_week")
        batch_op.drop_index("ix_plan_owner_user")
        batch_op.drop_index("ix_plan_owner_household")
        batch_op.drop_index(batch_op.f("ix_meal_plan_entries_week_start"))
        batch_op.drop_index(batch_op.f("ix_meal_plan_entries_user_id"))

    op.drop_table("meal_plan_entries")
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_msg_conv_created")
        batch_op.drop_index(batch_op.f("ix_agent_messages_conversation_id"))

    op.drop_table("agent_messages")
    with op.batch_alter_table("week_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_week_templates_user_id"))

    op.drop_table("week_templates")
    with op.batch_alter_table("shopping_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shopping_items_week_start"))
        batch_op.drop_index(batch_op.f("ix_shopping_items_user_id"))
        batch_op.drop_index("ix_shop_user_week")
        batch_op.drop_index("ix_shop_owner_user_week")
        batch_op.drop_index("ix_shop_owner_household_week")

    op.drop_table("shopping_items")
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipes_user_id"))
        batch_op.drop_index("ix_recipes_owner_user")
        batch_op.drop_index("ix_recipes_owner_household")

    op.drop_table("recipes")
    with op.batch_alter_table("household_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_members_household_id"))

    op.drop_table("household_members")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_prefix"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))

    op.drop_table("api_keys")
    op.drop_table("agent_settings")
    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_conversations_user_id"))

    op.drop_table("agent_conversations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("households")
    # ### end Alembic commands ###
